### PR TITLE
Rev version

### PR DESCRIPTION
**Pull request by devoncarew**
Rev to the latest service protocol spec. I don't think we want to land this just yet; I see two potential issue in the spec changes.

One, there's a reference to an undefined type: `@VM`. I patched the spec file, but just enough to make the generator happy.

Two, a type changed from a list to a scalar value. Again, I patched the file, but don't know if this is the fix.

### CODE REVIEW

**Comment by devoncarew** [comment]
first patch: https://github.com/dart-lang/vm_service_drivers/commit/c7af957c59313f654930cc76df82b54d971ddcad
2nd: https://github.com/dart-lang/vm_service_drivers/commit/ddc3088c1c1a9374bf030a60e85501f050e95c98

@johnmccutchan @turnidge @danrubel

**Comment by johnmccutchan** [comment]
@devoncarew Thanks. Both of the fixes are correct, I've put together a CL for the runtime here:

https://codereview.chromium.org/1396603004/

**Comment by danrubel** [comment]
LGTM, but it would be great to have some more information/guidance about VMUpdate and fixed ids. Comment added to https://codereview.chromium.org/1396603004/

**Comment by devoncarew** [comment]
Merging - I think the build failure was intermittent.

**Pull request merged**
