### PR TITLE
update to 3.0 spec

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
Not sure about the failure:

```
Dart process started - port 40753
     [java] Sample out: Observatory listening on http://127.0.0.1:40753
     [java] Exception in thread "main" java.lang.RuntimeException: Failed to connect to the VM vmService service
     [java] 	at org.dartlang.vm.service.VmServiceTest.vmConnect(Unknown Source)
     [java] 	at org.dartlang.vm.service.VmServiceTest.main(Unknown Source)
     [java] Caused by: java.io.IOException: Failed to connect: ws://localhost:40753/ws
     [java] 	at org.dartlang.vm.service.VmServiceBase.connect(VmServiceBase.java:118)
     [java] 	at org.dartlang.vm.service.VmServiceBase.localConnect(VmServiceBase.java:173)
```

The Dart version is able to connect when running its smoke test.

**Comment by danrubel** [comment]
And the java test runs fine on my desktop, so why does it fail here?

**Comment by danrubel** [comment]
Does travis have any inter-process communication restrictions?
Or any restrictions on port numbers used by the test?

**Comment by devoncarew** [comment]
I don't know - I'd guess anything above 1024 is legal -

**Comment by devoncarew** [comment]
Super awesome that we're able to update both libraries to the new spec just w/ additional code gen.

Perhaps try switching travis over to using the dev build of the sdk?

**Comment by devoncarew** [comment]
Add the line `dart: dev` into the travis file, or test on both sdks at the same time by adding two lines: https://github.com/dart-lang/dartdoc/blob/master/.travis.yml#L3

**Comment by danrubel** [comment]
@devoncarew Apparently hard coding the port to 7575 works for travis. PTAL

**Comment by devoncarew** [comment]
lgtm!

**Comment by danrubel** [comment]
Per "dart: dev" comment above... https://github.com/dart-lang/vm_service_drivers/pull/64

**Pull request merged**
