### PR TITLE
add callServiceExtension to VmServiceInterface 

### PR DESCRIPTION
**Pull request by jakemac53**
The VmServer implementation also now forwards any methods starting with 'ext.' to that method.

### CODE REVIEW

**Comment by jakemac53** [comment]
Hmm, I guess services registered via the protocol don't have to prefix with `ext.`, which makes this more complicated, this will work for anything registered through `dart:developer` though.

**Comment by jakemac53** [comment]
Actually, I think we will have to handle client registered extensions in the VmServer impl anyways, since that is the only thing that knows which client to send the requests to (the service doesn't know anything about connections at all).

So I will revert the last commit here and leave it as is, and follow up with a PR that adds support for forwarding client registered extensions to the proper client in the VmServer itself.

**Comment by devoncarew** [comment]
> Hmm, I guess services registered via the protocol don't have to prefix with `ext.`

Yeah, that's a convention, but not enforced by anything.

**Comment by devoncarew** [comment]
Let me know when this is ready for review -

**Comment by jakemac53** [comment]
> > Hmm, I guess services registered via the protocol don't have to prefix with `ext.`
> 
> Yeah, that's a convention, but not enforced by anything.

It is enforced in `dart:developer`, so its a bit unfortunate that it isn't enforced in the protocol :(. But, it isn't to difficult to work around.

**Comment by jakemac53** [comment]
@devoncarew You can go ahead and review this PR whenever, I am working on a followup now that is a bit larger of a refactor to handle routing the service registered handlers to the clients that registered them, but I think its fine to separate them out.

**Pull request merged**
