### PR TITLE
Updated for protocol v3.22

### PR DESCRIPTION
**Pull request by bkonyi**
- `registerService` is now a public RPC
- `Service` is now a public stream
- `ServiceRegistered` and `ServiceUnregistered` are now public events

Depends on [this VM CL](https://dart-review.googlesource.com/c/sdk/+/108366).

### CODE REVIEW

**Comment by devoncarew** [comment]
The test failure (https://travis-ci.org/dart-lang/vm_service_drivers/builds/556017227#L344) is likely related to the fact that the the dev sdk is on 3.20 of the service protocol.

**Comment by DanTup** [comment]
To make sure I understand correctly, this changes `_registerService` to `registerService` but there is no change to the `ServiceRegistered` event?

VS Code doesn't use `_registerService`, though does listen for `ServiceRegistered` events (to check if hot reload etc. are available). It sounds like I might not need to change anything there?

**Comment by DanTup** [comment]
Oh, I missed the stream name changed too. I guess it's safe for me to just change:

```
this.observatory.on("_Service", (event: VMEvent) => this.handleServiceEvent(event));
```

to

```ts
this.observatory.on("_Service", (event: VMEvent) => this.handleServiceEvent(event));
this.observatory.on("Service", (event: VMEvent) => this.handleServiceEvent(event));
```

Since it'll only send via one of them? (This would just avoid having to tweak the code to get the protocol version prior to setting up those listeners).

**Comment by devoncarew** [comment]
Yup, subscribing to both streams sounds good (note that one will then
always return an error result).

**Comment by bkonyi** [comment]
> lgtm!
> 
> When updating clients, we'll need them to call the older methods and expect the older events (`_registerService`, `_Service`, ...) pre 3.22, and the newer ones after.
> 
> The four clients using the service methods are VS Code (cc @DanTup), DevTools (cc @kenzieschmoll), the Flutter IntelliJ plugin, and flutter_tools.

Right, that makes sense. That's typically something we do manually on the client side, not in this package, correct?

**Comment by DanTup** [comment]
Don't these changes (for vm_service_lib) assume it'll never connect to a VM pre-these changes? Eg. if DevTools updated to these changes and shipped, wouldn't people with Flutter stable break?

It seems like there should be some logic in here based on the version of the VM it connects to?

**Comment by DanTup** [comment]
Also - should `SERVICE_PROTOCOL_MINOR_VERSION` be updated in the SDK CL?

**Comment by bkonyi** [comment]
> Don't these changes (for vm_service_lib) assume it'll never connect to a VM pre-these changes? Eg. if DevTools updated to these changes and shipped, wouldn't people with Flutter stable break?
> 
> It seems like there should be some logic in here based on the version of the VM it connects to?

Yes, that's the case. Unfortunately, these were private RPCs and streams that should have been made public before being used outside of Observatory, so clients which have relied on the private RPCs in the past will need to handle the case where an older version of the protocol is being used.

> Also - should SERVICE_PROTOCOL_MINOR_VERSION be updated in the SDK CL?

I always forget to update that... good catch, thanks!

**Comment by devoncarew** [comment]
> Don't these changes (for vm_service_lib) assume it'll never connect to a VM pre-these changes? Eg. if DevTools updated to these changes and shipped, wouldn't people with Flutter stable break?

Yup, for sure. For previous changes like this, we put the protocol version detection logic in the clients. They'll then either call the older private APIs manually, or the newer public APIs (via these new methods in the library).

**Comment by DanTup** [comment]
Ok cool, sounds like it's covered - as long as clients don't update to this version without implementing the version checking/manually calling the old methods at the same time.

Since I expect this won't be the last VM service change, I'm gonna add a proper version check rather than just hacking it as I mentioned above.

@bkonyi do you have an idea of when this is likely to land? It'd be nice to get updates in advance so it doesn't start affect users.

**Comment by bkonyi** [comment]
> Ok cool, sounds like it's covered - as long as clients don't update to this version without implementing the version checking/manually calling the old methods at the same time.
> 
> Since I expect this won't be the last VM service change, I'm gonna add a proper version check rather than just hacking it as I mentioned above.
> 
> @bkonyi do you have an idea of when this is likely to land? It'd be nice to get updates in advance so it doesn't start affect users.

I'd like to land this PR today, assuming the SDK change goes in (can't see why it won't land today). However, it's not urgent so I can wait if need be.

**Comment by DanTup** [comment]
Dart-Code PR is https://github.com/Dart-Code/Dart-Code/pull/1844. I was planning a release in approx two weeks (I'm not sure about the other tools - @devoncarew?).

If it's merged before the tools are updated, people on Flutter master (once it hits there) might seeing issues (for ex. hot reload being disabled since we didn't see the hot reload service register). I can try and release sooner (there's only really one significant thing already merged that needs a little more testing), though the other tools might be the limiting factor there. (@devoncarew is probably better placed to have an opinion on the impact of that, so I'd go with whatever his opinion is :-))

**Comment by kenzieschmoll** [comment]
FYI @DanTup - see this [PR](https://github.com/flutter/devtools/pull/747/files#diff-ec9a288c13a865c97f8b2fc18ab8d1b9) for how we check service protocol version in devtools and call the private/public method accordingly.

**Comment by DanTup** [comment]
@kenzieschmoll thanks! I did something similar, though wrapped the version checks up in properties of a "capabilities" class (https://github.com/Dart-Code/Dart-Code/pull/1844/files#diff-873c1044ed47a92f85176715fd3fe218R400). This is the same as I do for analyzer/flutter/flutter daemon/etc. (apparently there are a lot of version checks!) and makes it easy to review them periodically to see what can be dropped :-)

**Comment by DanTup** [comment]
> The four clients using the service methods are VS Code (cc @DanTup), DevTools (cc @kenzieschmoll), the Flutter IntelliJ plugin, and flutter_tools.

I think `webdev` might be using this too? (cc @jakemac53 @grouma )

https://github.com/dart-lang/webdev/blob/90c23b4a6bc8c03eab39485f1cd92bd008a99df6/dwds/lib/src/dwds_vm_client.dart#L59

**Comment by jakemac53** [comment]
Yep webdev both implements the protocol and also calls it. We pin our version of vm_service_lib though, so as long as the clients are looking at the version number of the protocol (and not for instance the dart sdk version) then everything should work out fine.

**Comment by DanTup** [comment]
@jakemac53 I was thinking that if you don't do anything, you'll start failing against new VMs (since `_registerService` goes away and that's what your pinned version of this lib will call when you call `registerService`?). I think webdev may need conditional logic similar to the DevTools code Kenzie linked above?

**Comment by jakemac53** [comment]
We don't call the vm implementation of the vm service though - we register it with our own implementation which is pinned.

**Comment by DanTup** [comment]
Whoops! I somewhat got confused about what your proxy did for a while then (thinking it was connecting to a real VM) but of course that's not its job - you're talking to a browser :-)

**Comment by jakemac53** [comment]
right, "proxy" sort of makes it sound like we are proxying to a real dart vm but we are actually proxying to the chrome debug protocol :).

**Pull request merged**
