### PR TITLE
Bump to service protocol 3.3

### PR DESCRIPTION
**Pull request by johnmccutchan**

### CODE REVIEW

**Comment by johnmccutchan** [comment]
@rmacnak-google

**Comment by rmacnak-google** [comment]
LGTM

**Comment by devoncarew** [comment]
@johnmccutchan, the formatting diffs are from using a different version of the formatter (probably a 1.14/1.15 thing).

The travis failure is a known issue on the Java generation side; the dart portion of this passed.

In this PR or a later one (happy to do it), we'll need to rev the pubspec version and add a corresponding entry to the changelog.

**Comment by johnmccutchan** [comment]
@devoncarew I'll do the bump in this release. Also, can you add johnmccutchan@ as an uploader for the pub package?

**Pull request merged**
