### PR TITLE
add an initial ant file

### PR DESCRIPTION
**Pull request by devoncarew**
Fix https://github.com/dart-lang/vm_service_drivers/issues/21, and some work towards building the jars and testing on travis.

@danrubel

### CODE REVIEW

**Comment by danrubel** [comment]
LGTM but travis build fails?

**Comment by devoncarew** [comment]
oops

**Comment by devoncarew** [comment]
Lints!

https://travis-ci.org/dart-lang/vm_service_drivers/builds/79907604#L236

**Comment by danrubel** [comment]
Nice!

**Pull request merged**
